# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZynqWithPwm.xdc

# Block Designs: bd/ZynqQWithPwm/ZynqQWithPwm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqQWithPwm || ORIG_REF_NAME==ZynqQWithPwm} -quiet] -quiet

# IP: bd/ZynqQWithPwm/ip/ZynqQWithPwm_enhancedPwmAXI_0_0/ZynqQWithPwm_enhancedPwmAXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqQWithPwm_enhancedPwmAXI_0_0 || ORIG_REF_NAME==ZynqQWithPwm_enhancedPwmAXI_0_0} -quiet] -quiet

# IP: bd/ZynqQWithPwm/ip/ZynqQWithPwm_processing_system7_0_0/ZynqQWithPwm_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqQWithPwm_processing_system7_0_0 || ORIG_REF_NAME==ZynqQWithPwm_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZynqQWithPwm/ip/ZynqQWithPwm_axi_smc_0/ZynqQWithPwm_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqQWithPwm_axi_smc_0 || ORIG_REF_NAME==ZynqQWithPwm_axi_smc_0} -quiet] -quiet

# IP: bd/ZynqQWithPwm/ip/ZynqQWithPwm_rst_ps7_0_50M_0/ZynqQWithPwm_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqQWithPwm_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZynqQWithPwm_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/EENG 484/ZynqWithPwm/ZynqWithPwm.gen/sources_1/bd/ZynqQWithPwm/ZynqQWithPwm_ooc.xdc
