transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/xil_defaultlib
vlib riviera/blk_mem_gen_v8_4_11
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_21
vlib riviera/processing_system7_vip_v1_0_23
vlib riviera/xlconstant_v1_1_10
vlib riviera/proc_sys_reset_v5_0_17
vlib riviera/smartconnect_v1_0
vlib riviera/axi_register_slice_v2_1_35

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap xil_defaultlib riviera/xil_defaultlib
vmap blk_mem_gen_v8_4_11 riviera/blk_mem_gen_v8_4_11
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_21 riviera/axi_vip_v1_1_21
vmap processing_system7_vip_v1_0_23 riviera/processing_system7_vip_v1_0_23
vmap xlconstant_v1_1_10 riviera/xlconstant_v1_1_10
vmap proc_sys_reset_v5_0_17 riviera/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_register_slice_v2_1_35 riviera/axi_register_slice_v2_1_35

vlog -work xilinx_vip  -incr "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"C:/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/870b/hdl/enhancedPwmAXI_slave_lite_v1_0_S00_AXI.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/870b/src/basicBuildingBlocksVhdl_package.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/870b/src/enhancedPwm.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/870b/src/genericComparator.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/870b/src/genericCounter.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/870b/hdl/enhancedPwmAXI.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_enhancedPwmAXI_0_0/sim/acquireToHDMIwithZynq_enhancedPwmAXI_0_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1/clk_wiz_0_clk_wiz.v" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1/clk_wiz_0.v" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/hdmi_tx_0_1/hdl/encode.v" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/hdmi_tx_0_1/hdl/serdes_10_to_1.v" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/hdmi_tx_0_1/hdl/srldelay.v" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/hdmi_tx_0_1/hdl/hdmi_tx_v1_0.v" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/hdmi_tx_0_1/sim/hdmi_tx_0.v" \

vlog -work blk_mem_gen_v8_4_11  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/blk_mem_gen_0_1/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/blk_mem_gen_0_1/sim/blk_mem_gen_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/hdl/acquireToDisplay_AXI_slave_lite_v1_0_S00_AXI.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/scopeToHdmi_package.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/acquireToHDMI_package.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/acquireToHDMI.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/acquireToHDMI_datapath.vhdl" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/acquireToHDMI_fsm.vhdl" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/dataToPixel.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/flagRegister.vhdl" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/genericMux4x1.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/genericRegister.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/scopeFace.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/src/videoSignalGenerator.vhdl" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0a01/hdl/acquireToDisplay_AXI.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/sim/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0.vhd" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_21  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_23  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_processing_system7_0_0/sim/acquireToHDMIwithZynq_processing_system7_0_0.v" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/sim/bd_6da4.v" \

vlog -work xlconstant_v1_1_10  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_0/sim/bd_6da4_one_0.v" \

vcom -work proc_sys_reset_v5_0_17 -93  -incr \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_1/sim/bd_6da4_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_2/sim/bd_6da4_arinsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_3/sim/bd_6da4_rinsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_4/sim/bd_6da4_awinsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_5/sim/bd_6da4_winsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_6/sim/bd_6da4_binsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_7/sim/bd_6da4_aroutsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_8/sim/bd_6da4_routsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_9/sim/bd_6da4_awoutsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_10/sim/bd_6da4_woutsw_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_11/sim/bd_6da4_boutsw_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_12/sim/bd_6da4_arni_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_13/sim/bd_6da4_rni_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_14/sim/bd_6da4_awni_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_15/sim/bd_6da4_wni_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_16/sim/bd_6da4_bni_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_17/sim/bd_6da4_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_18/sim/bd_6da4_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_19/sim/bd_6da4_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_20/sim/bd_6da4_s00a2s_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_21/sim/bd_6da4_sarn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_22/sim/bd_6da4_srn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_23/sim/bd_6da4_sawn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_24/sim/bd_6da4_swn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_25/sim/bd_6da4_sbn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_26/sim/bd_6da4_m00s2a_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_27/sim/bd_6da4_m00arn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_28/sim/bd_6da4_m00rn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_29/sim/bd_6da4_m00awn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_30/sim/bd_6da4_m00wn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_31/sim/bd_6da4_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_32/sim/bd_6da4_m00e_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_33/sim/bd_6da4_m01s2a_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_34/sim/bd_6da4_m01arn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_35/sim/bd_6da4_m01rn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_36/sim/bd_6da4_m01awn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_37/sim/bd_6da4_m01wn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_38/sim/bd_6da4_m01bn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_39/sim/bd_6da4_m01e_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_40/sim/bd_6da4_m02s2a_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_41/sim/bd_6da4_m02arn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_42/sim/bd_6da4_m02rn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_43/sim/bd_6da4_m02awn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_44/sim/bd_6da4_m02wn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_45/sim/bd_6da4_m02bn_0.sv" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/bd_0/ip/ip_46/sim/bd_6da4_m02e_0.sv" \

vlog -work axi_register_slice_v2_1_35  -incr -v2k5 "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../../Xilinx/2025.1/Vivado/data/rsb/busdef" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/src/clk_wiz_0_1" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/ec67/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/6cfa/hdl" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/f0b6/hdl/verilog" "+incdir+../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ipshared/a8e4/hdl/verilog" "+incdir+C:/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l blk_mem_gen_v8_4_11 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/sim/acquireToHDMIwithZynq_axi_smc_0.sv" \

vcom -work xil_defaultlib -93  -incr \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_rst_ps7_0_50M_0/sim/acquireToHDMIwithZynq_rst_ps7_0_50M_0.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_enhancedPwmAXI_1_0/sim/acquireToHDMIwithZynq_enhancedPwmAXI_1_0.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/sim/acquireToHDMIwithZynq.vhd" \
"../../../lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/hdl/acquireToHDMIwithZynq_wrapper.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

