# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab6constraints.xdc

# Block Designs: bd/acquireToHDMIwithZynq/acquireToHDMIwithZynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acquireToHDMIwithZynq || ORIG_REF_NAME==acquireToHDMIwithZynq} -quiet] -quiet

# IP: bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_enhancedPwmAXI_0_0/acquireToHDMIwithZynq_enhancedPwmAXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acquireToHDMIwithZynq_enhancedPwmAXI_0_0 || ORIG_REF_NAME==acquireToHDMIwithZynq_enhancedPwmAXI_0_0} -quiet] -quiet

# IP: bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0/acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0 || ORIG_REF_NAME==acquireToHDMIwithZynq_acquireToDisplay_AXI_0_0} -quiet] -quiet

# IP: bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_processing_system7_0_0/acquireToHDMIwithZynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acquireToHDMIwithZynq_processing_system7_0_0 || ORIG_REF_NAME==acquireToHDMIwithZynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_axi_smc_0/acquireToHDMIwithZynq_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acquireToHDMIwithZynq_axi_smc_0 || ORIG_REF_NAME==acquireToHDMIwithZynq_axi_smc_0} -quiet] -quiet

# IP: bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_rst_ps7_0_50M_0/acquireToHDMIwithZynq_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acquireToHDMIwithZynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==acquireToHDMIwithZynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_enhancedPwmAXI_1_0/acquireToHDMIwithZynq_enhancedPwmAXI_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acquireToHDMIwithZynq_enhancedPwmAXI_1_0 || ORIG_REF_NAME==acquireToHDMIwithZynq_enhancedPwmAXI_1_0} -quiet] -quiet

# XDC: c:/EENG 484/lab6acquireToHDMIwithZynq/lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/acquireToHDMIwithZynq_ooc.xdc
