# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/EENG 484/lab6acquireToHDMIwithZynq/lab6acquireToHDMIwithZynq.srcs/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_processing_system7_0_0/acquireToHDMIwithZynq_processing_system7_0_0.xci
# IP: The module: 'acquireToHDMIwithZynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EENG 484/lab6acquireToHDMIwithZynq/lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_processing_system7_0_0/acquireToHDMIwithZynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'acquireToHDMIwithZynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/EENG 484/lab6acquireToHDMIwithZynq/lab6acquireToHDMIwithZynq.srcs/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_processing_system7_0_0/acquireToHDMIwithZynq_processing_system7_0_0.xci
# IP: The module: 'acquireToHDMIwithZynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EENG 484/lab6acquireToHDMIwithZynq/lab6acquireToHDMIwithZynq.gen/sources_1/bd/acquireToHDMIwithZynq/ip/acquireToHDMIwithZynq_processing_system7_0_0/acquireToHDMIwithZynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'acquireToHDMIwithZynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
