# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/EENG 484/ZynqWithPwm/ZynqWithPwm.srcs/sources_1/bd/ZynqQWithPwm/ip/ZynqQWithPwm_rst_ps7_0_50M_0/ZynqQWithPwm_rst_ps7_0_50M_0.xci
# IP: The module: 'ZynqQWithPwm_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EENG 484/ZynqWithPwm/ZynqWithPwm.gen/sources_1/bd/ZynqQWithPwm/ip/ZynqQWithPwm_rst_ps7_0_50M_0/ZynqQWithPwm_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqQWithPwm_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/EENG 484/ZynqWithPwm/ZynqWithPwm.gen/sources_1/bd/ZynqQWithPwm/ip/ZynqQWithPwm_rst_ps7_0_50M_0/ZynqQWithPwm_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqQWithPwm_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/EENG 484/ZynqWithPwm/ZynqWithPwm.srcs/sources_1/bd/ZynqQWithPwm/ip/ZynqQWithPwm_rst_ps7_0_50M_0/ZynqQWithPwm_rst_ps7_0_50M_0.xci
# IP: The module: 'ZynqQWithPwm_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EENG 484/ZynqWithPwm/ZynqWithPwm.gen/sources_1/bd/ZynqQWithPwm/ip/ZynqQWithPwm_rst_ps7_0_50M_0/ZynqQWithPwm_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqQWithPwm_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/EENG 484/ZynqWithPwm/ZynqWithPwm.gen/sources_1/bd/ZynqQWithPwm/ip/ZynqQWithPwm_rst_ps7_0_50M_0/ZynqQWithPwm_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqQWithPwm_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
